# Generated by Django 4.2.6 on 2023-10-19 15:10

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_user_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Уникальный идентификатор чата телеграм'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(max_length=150, unique=True, validators=[users.validators.TelegramNicknameValidator()], verbose_name='Уникальный идентификатор пользователя телеграм'),
        ),
    ]
