# Generated by Django 4.2.6 on 2023-10-18 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.DurationField(verbose_name='Интервал между напоминаниями, часы')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время старта')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное напоминание')),
                ('last_event', models.DateTimeField(blank=True, null=True, verbose_name='Время последнего напоминания')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.TimeField(blank=True, null=True, verbose_name='Время выполнения')),
                ('tuesday', models.TimeField(blank=True, null=True, verbose_name='Время выполнения')),
                ('wednesday', models.TimeField(blank=True, null=True, verbose_name='Время выполнения')),
                ('thursday', models.TimeField(blank=True, null=True, verbose_name='Время выполнения')),
                ('friday', models.TimeField(blank=True, null=True, verbose_name='Время выполнения')),
                ('saturday', models.TimeField(blank=True, null=True, verbose_name='Время выполнения')),
                ('sunday', models.TimeField(blank=True, null=True, verbose_name='Время выполнения')),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=200, null=True, verbose_name='Место')),
                ('operation', models.CharField(max_length=200, verbose_name='Действие')),
                ('is_enjoyable', models.BooleanField(default=False, verbose_name='Приятная привычка')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение')),
                ('lead_time', models.DurationField(blank=True, null=True, verbose_name='Продолжительность выполнения, секунды')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная')),
                ('interval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.interval', verbose_name='Интервал')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.schedule', verbose_name='Расписание')),
            ],
        ),
    ]
