# Generated by Django 4.2.6 on 2023-10-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
        migrations.AlterModelOptions(
            name='interval',
            options={'verbose_name': 'Интервал', 'verbose_name_plural': 'Интервалы'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Где'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='friday',
            field=models.TimeField(blank=True, null=True, verbose_name='Пятница, время выполнения'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday',
            field=models.TimeField(blank=True, null=True, verbose_name='Понедельник, время выполнения'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='saturday',
            field=models.TimeField(blank=True, null=True, verbose_name='Суббота, время выполнения'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sunday',
            field=models.TimeField(blank=True, null=True, verbose_name='Воскресенье, время выполнения'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursday',
            field=models.TimeField(blank=True, null=True, verbose_name='Четверг, время выполнения'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday',
            field=models.TimeField(blank=True, null=True, verbose_name='Вторник, время выполнения'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday',
            field=models.TimeField(blank=True, null=True, verbose_name='Среда, время выполнения'),
        ),
    ]
