# Generated by Django 4.2.6 on 2023-10-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_options_alter_interval_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='last_event',
            field=models.TimeField(blank=True, null=True, verbose_name='Время последнего напоминания'),
        ),
    ]
