# Generated by Django 4.2.6 on 2023-10-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_remove_schedule_last_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Активное напоминание'),
        ),
    ]
