# Generated by Django 4.2.6 on 2023-10-20 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_interval_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interval',
            name='is_active',
        ),
    ]
